### ISSUE TITLE
Comment on sample ID convention

### ISSUE THREAD

**Issue by budschi** [FAIRmat-Experimental/Area_A_application_definitions#1]
Please comment on the [sample ID convention](https://github.com/FAIRmat-Experimental/Area_A_application_definitions/blob/main/sampleid_workshop/sampleid.md) here in the issue. Please give us your **feedback until Friday 17.06.2022**. Based on our sample ID convention we will then create a base class that can be used within NOMAD.

Here is the content of [sampleid.md](https://github.com/FAIRmat-Experimental/Area_A_application_definitions/blob/main/sampleid_workshop/sampleid.md):

# Convention for the generation of the full sample ID

The goal is to find a human readable sample id convention, which is simple, understandable and still having chances of becoming unique.

The ID consists of the following components:
* `institute`: Abreviation of the home institute of the sample owner e.g. `HZB`, `PDI`...
* `owner_alias`: alias of the owner of the sample, e.g. `oah`
* `creation_date`: Date of the creation of the sample in the form of `YYYYMMDD`
* `sample_short_name`: a short name of the sample (the identifier scribed on the smaple, or in the sample box), e.g. `4001-8`, `YAG-2-34`. This is to be managed and decided internally by the labs, although we recomend to avoid the following characters in it: "`_`", "`/`", "`\`" and "`.`" 

The individual components are seperated by underscores (`_`).  
Spaces in any of the individual components will be replaced with hyphens (`-`).

Full example for a full sample ID: `hzb_oah_20200602_4001-08`

# Convention for a **sub**sample `sample_short_name`

Sometimes, a sample gets divided to share a part with a collabotor or simply to perform further experiments in these dived parts. These divided parts then becaome sub samples. 

The subsamples short names will be generated by appending an hyphen (`-`) followed by a letter to the *parent* `sample_short_name`, e.g. `4001-8-a`, `4001-8-b` for an hypothetical parent sample with a `sample_short_name` of `4001-8`.

**Comment by Pepe-Marquez** [comment]
> 
In the case of a Nomad base class, the creation date will be a datetime object. At the time of using this part to add it to the full sample_id, then it will be formated to YYYYMMDD. In other words, you will have a creation_date field in any date_time format and the conversion will be done at the time of writing the sample_id.

**Comment by datawomanHUB** [comment]
You could add that the sample ID convention is case insensitive.

**Comment by tomio13** [comment]
The aim of the game is not simply making something human readable for information storage, but small enough for sample handling. One can expect on the short run that not all labs have label printers, thus a user writing the string on a sample with pen would possibly want to:
  * have all capital letters
  * minimize amount to write
In most cases user acronym, date (YYYYMMDD or even YYMMDD) and a short serial does the job, hours and minutes / time zone being not critical (anyway often creating a sample is not a 5 seconds process to have a sharp time stamp attached).
